apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-suc3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-suc3@sha256:4267406a7130794ef21c19144d39b61ca550c8274434224ac7620dc20f67ae06
        name: my-nodejs
        resources: {}
status: {}
